language: java

env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx5g"

jdk:
- oraclejdk8

after_success:
- bash <(curl -s https://codecov.io/bash)

before_script:
  - cd PepGenome

before_deploy:
  - "mvn package"
