language: java

jdk:
- oraclejdk8

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
  - "mvn -DskipTests package"
  - export RELEASE_ZIP_FILE=$(ls target/pia-*.zip)
  - echo "deploying $RELEASE_ZIP_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: "wTjEsTWzBBSElbF3M8u7mWcashbSQh6cJs6VFvkWz0Vy+hMa/QDdtciCSLsUACBfIfr96LCK+BXjMEYtlyh+hQ6QdtzEHmb7QrxfrHgoe2iSBfYdFkiXITFUsKB6BHNklMMBcq40sx6AonposHojl4Cu3ETSABnbhzo1IKddJbOUz9h6ceU9lFsWH07jC30tdR2h/mNUSkOyfHrhDbyXA3NrmdDtw/OmwXORX+fL9Rbnp0XuJf9fB5e4s2YqXlOFB0xCN2atWQP26+p6RSwJQN2jWZ9GSuFYC362WFaSl0mV9PRgvq1xRidffdNcE0tVqwX+iT8yeZrxJ7XNzjP+/kBsKCipnd93FAxTM3uxa1Bm7fkv2W9D+xMKufntukPHKjg//DrwKNosg/72vEQvrYdnZW/EJeQAA6gLE7EwI4/2+TdQV6hAMZRAnhQOrAQ9NiZr2xMwp3eUGfH2zrwzPeYMjay0A0dOro4OVa1Gq/5XRrkXrIN4PafgJjS+Wypwo1Bvq2SKr+ntDaNbaKEzT268BNlhJFLmIFNWyG6JIf7bjE6JtBRBe2DJzvqjHjUQGtNo41pZznpAnvC5yIev864jwwKtbMasVv29fIpi9QsfmJgL9fSY3a1A3lxYXmdHTpix2AoUIYoivFRghDN4t6gbBIJkVrrC6eWumBqUcbo="
  file: "${RELEASE_ZIP_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
